config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "application#home"

  get "all", to: "application#all", as: "all"

  get "popular_photo", to: "application#popular_photo", as: "most_liked"

  resources :users do
    resources :photos
  end

  resources :photos do
    resources :likes
  end
  
  # for simple like feature
  # put "/photo/:id/like", to: "photos#like", as: "like"
end

app/models/photo.rb
class Photo < ApplicationRecord
     belongs_to :user
     has_many :likes, dependent: :destroy
     has_many :users_who_liked, through: :likes, source: :user

     validates_presence_of :img_url

     scope :public_photos, -> { where(public: "public") }
     scope :most_liked, -> { order("photos.likes_count DESC") }

     CHOICES = ["public", "private"]  
end

# Homework before Monday (contact via Slack)

# no model methods inside views -> helper_method
# code challenge: create a route called popular_photo. 
     # in this route you are to render the photo with the most likes

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :find_photos, only: [:show, :edit, :update, :destroy]
    # before_action :correct_users_photos, only: [:show, :edit, :update, :destroy]

    def index
        @photos = current_user.photos
    end

    def new
       @photo = Photo.new
    end
    
    def create
        @photo = current_user.photos.build(photo_params)
        @photo.user_id = current_user.id
        
        if @photo.save
            flash.notice = "upload successful"

            redirect_to user_photo_path(current_user, @photo)
        else
            @photo.errors.full_messages

            render :new
            # redirect_to root_path
        end
    end

    def show
        # find_photos
    end

    def edit
        # find_photos
    end

    def update
        if @photo.update(photo_params)

            redirect_to user_photo_path(current_user, @photo)
        else
            @photo.errors.full_messages
            
            render :edit
        end
    end

    def destroy
        @photo.destroy
    
        redirect_to user_photos_path(current_user)
    end

    # def like
    #     find_photos

    #     Like.create(user_id: current_user.id, photo_id: @photo.id)

    #     redirect_to photo_path(@photo)
    # end

    private 
        def find_photos
            @photo = Photo.find(params[:id])
        end

        def photo_params
            params.require(:photo).permit(:img_url, :description, :public, :user_id)
        end

        # def correct_users_photos
        #     @photo = current_user.photos.find_by(id: params[:id])
        # end
end

app/views/photos/_errors.html.erb
<% if @photo.errors.any? %>
    <% @photo.errors.full_messages.each do |message| %>
        <%= message %>
    <% end %>
<% end %>

app/views/photos/_form.html.erb
<label>photo url:</label>
<%= text_field_tag :img_url, @photo.img_url %><br /><br />

<label>description:</label>
<%= text_field_tag :description, @photo.description %>

app/views/photos/edit.html.erb
<h1><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></h1>

<% if @photo.user_id == current_user.id %>
    <h2>edit photo</h2>

    <%= link_to "back", :back %><br><br>

    <%= render "errors" %>

    <%= form_with model: @photo, url: user_photo_path(current_user, @photo), method: "patch" do |f| %>
        <!-- <%= render "form" %> -->

        <%= f.label "photo url" %>
        <%= f.text_field :img_url %><br><br>

        <%= f.label "description" %>
        <%= f.text_field :description %>

        <%= f.collection_select :public, Photo::CHOICES, :to_s, :to_s %><br /><br />

        <%= f.submit "update" %>
    <% end %>

    <br><%= image_tag(@photo.img_url) %><br><br><br>

    <%= button_to "delete photo", @photo, method: "delete" %><br />
<% else %>
    <h1><div class="logo"><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></div> 🅉🄸🄶🅉🄰🄶</h1> 
        <%= link_to "sign up", new_user_registration_path %><br />
        <%= link_to "log in", new_user_session_path %>
<% end %>

app/views/photos/index.html.erb
<h1><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></h1>
<h2><%= current_user.name %>'s photos</h2>

<ul>
    <li id = "home"><%= link_to "home", root_path %></li>
    <li id = "new-photo"><%= link_to "upload photo", new_user_photo_path(current_user) %></li>
    <%= button_to "sign out", destroy_user_session_path, method: "delete"%><br><br><br>
</ul>

<% @photos.each do |photo| %>
    <%= link_to(image_tag(photo.img_url, height: 200, width: 200), user_photo_path(current_user, photo)) %>
<% end %>

app/views/photos/new.html.erb
<h1><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></h1\>
<h2>upload a photo</h2>

<%= link_to "back", :back, { :class => "back-link" } %><br><br>

<%= render "errors" %>

<%= form_with model: @photo, url: user_photos_path(current_user, @photo), method: "post" do |f| %>
    <!-- <%= render "form" %> -->

    <%= f.label "photo url" %>
    <%= f.text_field :img_url %><br><br>

    <%= f.label "description" %>
    <%= f.text_field :description %>

    <%= f.collection_select :public, Photo::CHOICES, :to_s, :to_s %><br /><br />

    <%= f.submit "upload" %>
<% end %>

app/views/photos/show.html.erb
<h1><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></h1>

<% if @photo.user_id == current_user.id %>
<h3><%= @photo.description %> (<%= @photo.public %>)</h3> 

<ul>
    <li id = "home"><%= link_to "home", root_path %></li>
    <li id = "public-feed"><%= link_to "public feed", all_path %></li>
    <li id = "my-photos"><%= link_to "my photos", user_photos_path(current_user) %></li>
    <li id = "new-photo"><%= link_to "upload photo", new_user_photo_path(current_user) %></li>
    <li id = "edit"><%= link_to "edit", edit_user_photo_path(current_user, @photo) %></li><br><br>
</ul>
    <%= image_tag(@photo.img_url) %><br />

    <div>
        <%= button_to "delete photo", @photo, method: "delete" %><br />
    </div>
<% else %>
    <h1><div class="logo"><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></div> 🅉🄸🄶🅉🄰🄶</h1> 
        <%= link_to "sign up", new_user_registration_path %><br />
        <%= link_to "log in", new_user_session_path %>
<% end %>