config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "application#home"

  get "all", to: "application#all", as: "all"

  get "popular_photo", to: "application#popular_photo", as: "most_liked"

  resources :users do
    resources :photos
  end

  resources :photos do
    resources :likes
  end
  
  # for simple like feature
  # put "/photo/:id/like", to: "photos#like", as: "like"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :most_liked_photo

    def all
        @photos = Photo.all.public_photos
        # @photos = Photo.all.where(:public => "public")
    end

    def most_liked_photo
        @liked_photo = all.most_liked.first
        # all.most_liked.first
    end
    # helper_method :most_liked_photo

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

# code challenge: create a route called popular_photo. 
# in this route you are to render the photo with the most likes

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/all.html.erb
<h1><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></h1>
<h2>public feed</h2>

<ul>
    <li id = "home"><%= link_to "home", root_path %><br /></li>
    <li id = "most-liked"><%= link_to "most liked photo", most_liked_path %></li>
    <li id = "my-photos"><%= link_to "my photos", user_photos_path(current_user) %></li>
    <li id = "new-photo"><%= link_to "upload photo", new_user_photo_path(current_user) %></li>
    <%= button_to "sign out", destroy_user_session_path, method: "delete"%><br><br>
</ul>
<% @photos.each do |photo| %>
    <%= image_tag(photo.img_url, height: 200, width: 200) %>
    <%= photo.likes.count %> <%= (photo.likes.count) == 1 ? "like" : "likes" %>
   <!-- | <%= photo.likes.where(type: "super like").count %> <%= (photo.likes.where(type: "super like").count) == 1 ? "super like" : "super likes" %> -->
    <%= button_to "like", photo_likes_path(photo), method: :post %><br>
    <!-- <%= button_to "super like", photo_likes_path(photo), method: :post %><br><br><br> -->

    <!-- <%= form_with model: @like, url: photo_likes_path(photo), method: "post" do |f| %> -->
    <!--    <%= f.collection_select :type, Like::CHOICES, :to_s, :to_s %> -->
    <!--    <%= f.submit "submit like" %> -->
    <!-- <% end %><br><br><br> -->
<% end %>

app/views/application/home.html.erb
<h1><div class="logo"><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></div> 🅉🄸🄶🅉🄰🄶</h1> 

<% if current_user %>  
    <ul>
        <li id="public-feed"><%= link_to "public feed", all_path %></li>
        <li id="my-photos"><%= link_to "my photos", user_photos_path(current_user) %></li>
        <li id="new-photo"><%= link_to "upload photo", new_user_photo_path(current_user) %></li>
        <%= button_to "sign out", destroy_user_session_path, method: "delete"%><br><br>
    </ul>
    <% pic = current_user.photos.last %>
    <% if pic&.img_url %>
        <%= link_to(image_tag(pic.img_url, height: 350, width: 350), user_photos_path(current_user)) %>
    <% end %>
<% else %>
   <center><div class="nav-container">
    <ul>
        <li id="sign-up"><%= link_to "sign up", new_user_registration_path %></li><br><br><br>
        <li id="log-in"><%= link_to "log in", new_user_session_path %></li><br><br>
    
        <%= button_to "log in with google", user_google_oauth2_omniauth_authorize_path %>
    </ul>
    </div></center>
<% end %>

app/views/application/popular_photo.html.erb
<h1><%= image_tag("boston-terrier-logo.jpg", height: "130", width: "130") %></h1>
<h2>most popular photo</h2>

<%= link_to "back", :back %><br><br>



<%= image_tag(@liked_photo.img_url, height: 400, width: 400) %>